[{
    "_id": 0,
    "value": {
      "8": {
        "variantClassification": ["3'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 24,
        "tAltCount": 11,
        "tAltFrac": 0.4583333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "14": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 109,
        "tAltCount": 28,
        "tAltFrac": 0.25688073394495414,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "25": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.381)"],
        "impact": ["MODERATE"],
        "tDepth": 17,
        "tAltCount": 4,
        "tAltFrac": 0.23529411764705882,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "27": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.998)"],
        "impact": ["MODERATE"],
        "tDepth": 67,
        "tAltCount": 16,
        "tAltFrac": 0.23880597014925373,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "36": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(1)", "possibly_damaging(0.862)"],
        "impact": ["MODERATE"],
        "tDepth": 74,
        "tAltCount": 21,
        "tAltFrac": 0.42857142857142855,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "39": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 24,
        "tAltCount": 9,
        "tAltFrac": 0.375,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "63": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.606)"],
        "impact": ["MODERATE"],
        "tDepth": 59,
        "tAltCount": 19,
        "tAltFrac": 0.3220338983050847,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "79": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.998)"],
        "impact": ["MODERATE"],
        "tDepth": 34,
        "tAltCount": 15,
        "tAltFrac": 0.4411764705882353,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "110": {
        "variantClassification": ["Frame_Shift_Del"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 53,
        "tAltCount": 9,
        "tAltFrac": 0.16981132075471697,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "120": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 18,
        "tAltCount": 9,
        "tAltFrac": 0.5,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "197": {
        "variantClassification": ["5'Flank"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 8,
        "tAltCount": 3,
        "tAltFrac": 0.375,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "246": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 35,
        "tAltCount": 10,
        "tAltFrac": 0.2857142857142857,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "256": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 12,
        "tAltCount": 4,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "272": {
        "variantClassification": ["5'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 27,
        "tAltCount": 10,
        "tAltFrac": 0.37037037037037035,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "276": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 21,
        "tAltCount": 7,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "282": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.756)"],
        "impact": ["MODERATE"],
        "tDepth": 61,
        "tAltCount": 18,
        "tAltFrac": 0.29508196721311475,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "286": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.029)"],
        "impact": ["MODERATE"],
        "tDepth": 13,
        "tAltCount": 6,
        "tAltFrac": 0.46153846153846156,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "298": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.008)"],
        "impact": ["MODERATE"],
        "tDepth": 73,
        "tAltCount": 18,
        "tAltFrac": 0.2465753424657534,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "304": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 129,
        "tAltCount": 41,
        "tAltFrac": 0.3178294573643411,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "307": {
        "variantClassification": ["Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 12,
        "tAltCount": 4,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "311": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.673)"],
        "impact": ["MODERATE"],
        "tDepth": 35,
        "tAltCount": 9,
        "tAltFrac": 0.2571428571428571,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "334": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.079)"],
        "impact": ["MODERATE"],
        "tDepth": 69,
        "tAltCount": 30,
        "tAltFrac": 0.43478260869565216,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "347": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.79)"],
        "impact": ["MODERATE"],
        "tDepth": 93,
        "tAltCount": 30,
        "tAltFrac": 0.3225806451612903,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "359": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.006)", "probably_damaging(0.99)"],
        "impact": ["MODERATE"],
        "tDepth": 71,
        "tAltCount": 25,
        "tAltFrac": 0.352112676056338,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "378": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.07)", "probably_damaging(0.915)"],
        "impact": ["MODERATE"],
        "tDepth": 72,
        "tAltCount": 16,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "386": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 100,
        "tAltCount": 25,
        "tAltFrac": 0.25,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "396": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.987)"],
        "impact": ["MODERATE"],
        "tDepth": 46,
        "tAltCount": 22,
        "tAltFrac": 0.4782608695652174,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "400": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 78,
        "tAltCount": 27,
        "tAltFrac": 0.34615384615384615,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "407": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 32,
        "tAltCount": 8,
        "tAltFrac": 0.25,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "423": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 37,
        "tAltCount": 20,
        "tAltFrac": 0.5405405405405406,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "425": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 65,
        "tAltCount": 27,
        "tAltFrac": 0.4153846153846154,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "429": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 52,
        "tAltCount": 20,
        "tAltFrac": 0.38461538461538464,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "431": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.006)"],
        "impact": ["MODERATE"],
        "tDepth": 59,
        "tAltCount": 21,
        "tAltFrac": 0.3559322033898305,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "433": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 77,
        "tAltCount": 28,
        "tAltFrac": 0.36363636363636365,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "441": {
        "variantClassification": ["Splice_Region", "Missense_Mutation"],
        "polyPhen": ["", "probably_damaging(1)"],
        "impact": ["LOW", "MODERATE"],
        "tDepth": 94,
        "tAltCount": 31,
        "tAltFrac": 0.32978723404255317,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "444": {
        "variantClassification": ["Splice_Region"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 35,
        "tAltCount": 15,
        "tAltFrac": 0.42857142857142855,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "451": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.943)"],
        "impact": ["MODERATE"],
        "tDepth": 90,
        "tAltCount": 24,
        "tAltFrac": 0.26666666666666666,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "461": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.609)"],
        "impact": ["MODERATE"],
        "tDepth": 79,
        "tAltCount": 23,
        "tAltFrac": 0.2911392405063291,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "468": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 46,
        "tAltCount": 10,
        "tAltFrac": 0.21739130434782608,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "474": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.046)"],
        "impact": ["MODERATE"],
        "tDepth": 41,
        "tAltCount": 18,
        "tAltFrac": 0.43902439024390244,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "479": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.164)"],
        "impact": ["MODERATE"],
        "tDepth": 40,
        "tAltCount": 16,
        "tAltFrac": 0.4,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "484": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.211)", "benign(0.113)"],
        "impact": ["MODERATE"],
        "tDepth": 34,
        "tAltCount": 16,
        "tAltFrac": 0.5333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "507": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 67,
        "tAltCount": 25,
        "tAltFrac": 0.373134328358209,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "513": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 29,
        "tAltCount": 10,
        "tAltFrac": 0.3448275862068966,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "520": {
        "variantClassification": ["3'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 22,
        "tAltCount": 5,
        "tAltFrac": 0.22727272727272727,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "522": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.138)"],
        "impact": ["MODERATE"],
        "tDepth": 57,
        "tAltCount": 24,
        "tAltFrac": 0.42105263157894735,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "526": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 45,
        "tAltCount": 6,
        "tAltFrac": 0.13333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "529": {
        "variantClassification": ["Missense_Mutation", "Silent"],
        "polyPhen": ["benign(0.003)", ""],
        "impact": ["MODERATE", "LOW"],
        "tDepth": 82,
        "tAltCount": 15,
        "tAltFrac": 0.26785714285714285,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "540": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["unknown(0)"],
        "impact": ["MODERATE"],
        "tDepth": 44,
        "tAltCount": 19,
        "tAltFrac": 0.4318181818181818,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "541": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 115,
        "tAltCount": 55,
        "tAltFrac": 0.4782608695652174,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "549": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.987)"],
        "impact": ["MODERATE"],
        "tDepth": 9,
        "tAltCount": 3,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "570": {
        "variantClassification": ["5'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 18,
        "tAltCount": 4,
        "tAltFrac": 0.2222222222222222,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "575": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.78)"],
        "impact": ["MODERATE"],
        "tDepth": 55,
        "tAltCount": 15,
        "tAltFrac": 0.2727272727272727,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "582": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 83,
        "tAltCount": 18,
        "tAltFrac": 0.37209302325581395,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "590": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.992)"],
        "impact": ["MODERATE"],
        "tDepth": 83,
        "tAltCount": 30,
        "tAltFrac": 0.3614457831325301,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "595": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 94,
        "tAltCount": 20,
        "tAltFrac": 0.2127659574468085,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "596": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.692)"],
        "impact": ["MODERATE"],
        "tDepth": 32,
        "tAltCount": 11,
        "tAltFrac": 0.34375,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "602": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 204,
        "tAltCount": 58,
        "tAltFrac": 0.28431372549019607,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "603": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.974)", "possibly_damaging(0.567)", "benign(0.387)"],
        "impact": ["MODERATE"],
        "tDepth": 195,
        "tAltCount": 63,
        "tAltFrac": 0.3230769230769231,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "608": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 72,
        "tAltCount": 20,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "632": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 70,
        "tAltCount": 15,
        "tAltFrac": 0.21428571428571427,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "636": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(1)"],
        "impact": ["MODERATE"],
        "tDepth": 110,
        "tAltCount": 40,
        "tAltFrac": 0.36363636363636365,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "642": {
        "variantClassification": ["Silent", "Missense_Mutation", "Splice_Site"],
        "polyPhen": ["", "probably_damaging(0.981)", "benign(0.005)"],
        "impact": ["LOW", "MODERATE", "HIGH"],
        "tDepth": 72,
        "tAltCount": 21,
        "tAltFrac": 0.3076923076923077,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "650": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.589)"],
        "impact": ["MODERATE"],
        "tDepth": 45,
        "tAltCount": 16,
        "tAltFrac": 0.35555555555555557,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "651": {
        "variantClassification": ["3'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 59,
        "tAltCount": 24,
        "tAltFrac": 0.4067796610169492,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "653": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.991)", "probably_damaging(0.999)", "probably_damaging(0.997)"],
        "impact": ["MODERATE"],
        "tDepth": 78,
        "tAltCount": 20,
        "tAltFrac": 0.28,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "664": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.078)"],
        "impact": ["MODERATE"],
        "tDepth": 36,
        "tAltCount": 12,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "674": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.04)"],
        "impact": ["MODERATE"],
        "tDepth": 53,
        "tAltCount": 21,
        "tAltFrac": 0.39622641509433965,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "708": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 48,
        "tAltCount": 16,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "710": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 70,
        "tAltCount": 30,
        "tAltFrac": 0.42857142857142855,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "718": {
        "variantClassification": ["3'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 8,
        "tAltCount": 3,
        "tAltFrac": 0.375,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "731": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 67,
        "tAltCount": 22,
        "tAltFrac": 0.3283582089552239,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "744": {
        "variantClassification": ["Splice_Region", "Missense_Mutation"],
        "polyPhen": ["", "possibly_damaging(0.72)"],
        "impact": ["LOW", "MODERATE"],
        "tDepth": 34,
        "tAltCount": 8,
        "tAltFrac": 0.3125,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "745": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.102)"],
        "impact": ["MODERATE"],
        "tDepth": 45,
        "tAltCount": 15,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "754": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 184,
        "tAltCount": 66,
        "tAltFrac": 0.358695652173913,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "769": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.999)"],
        "impact": ["MODERATE"],
        "tDepth": 46,
        "tAltCount": 16,
        "tAltFrac": 0.34782608695652173,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "771": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.025)"],
        "impact": ["MODERATE"],
        "tDepth": 51,
        "tAltCount": 14,
        "tAltFrac": 0.27450980392156865,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "794": {
        "variantClassification": ["Silent", "Intron"],
        "polyPhen": [""],
        "impact": ["LOW", "MODIFIER"],
        "tDepth": 49,
        "tAltCount": 13,
        "tAltFrac": 0.2653061224489796,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "796": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 81,
        "tAltCount": 15,
        "tAltFrac": 0.18518518518518517,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "806": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 19,
        "tAltCount": 7,
        "tAltFrac": 0.3684210526315789,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "807": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.004)"],
        "impact": ["MODERATE"],
        "tDepth": 22,
        "tAltCount": 4,
        "tAltFrac": 0.18181818181818182,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "819": {
        "variantClassification": ["RNA"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 45,
        "tAltCount": 16,
        "tAltFrac": 0.35555555555555557,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "820": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.014)"],
        "impact": ["MODERATE"],
        "tDepth": 82,
        "tAltCount": 23,
        "tAltFrac": 0.2804878048780488,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "824": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.121)"],
        "impact": ["MODERATE"],
        "tDepth": 95,
        "tAltCount": 36,
        "tAltFrac": 0.37894736842105264,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "842": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.003)"],
        "impact": ["MODERATE"],
        "tDepth": 11,
        "tAltCount": 4,
        "tAltFrac": 0.36363636363636365,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "845": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 47,
        "tAltCount": 18,
        "tAltFrac": 0.3829787234042553,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "853": {
        "variantClassification": ["Missense_Mutation", "Silent"],
        "polyPhen": ["benign(0.23)", ""],
        "impact": ["MODERATE", "LOW"],
        "tDepth": 33,
        "tAltCount": 14,
        "tAltFrac": 0.42424242424242425,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "867": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.003)"],
        "impact": ["MODERATE"],
        "tDepth": 29,
        "tAltCount": 11,
        "tAltFrac": 0.3793103448275862,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "883": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 18,
        "tAltCount": 8,
        "tAltFrac": 0.4444444444444444,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "887": {
        "variantClassification": ["5'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 15,
        "tAltCount": 4,
        "tAltFrac": 0.26666666666666666,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "913": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.081)", "benign(0)"],
        "impact": ["MODERATE"],
        "tDepth": 79,
        "tAltCount": 21,
        "tAltFrac": 0.26582278481012656,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "919": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.397)"],
        "impact": ["MODERATE"],
        "tDepth": 115,
        "tAltCount": 47,
        "tAltFrac": 0.40869565217391307,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "920": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 14,
        "tAltCount": 3,
        "tAltFrac": 0.21428571428571427,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "923": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 50,
        "tAltCount": 18,
        "tAltFrac": 0.36,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "924": {
        "variantClassification": ["Frame_Shift_Ins"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 34,
        "tAltCount": 17,
        "tAltFrac": 0.5,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "931": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 45,
        "tAltCount": 13,
        "tAltFrac": 0.28888888888888886,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "939": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.311)"],
        "impact": ["MODERATE"],
        "tDepth": 14,
        "tAltCount": 3,
        "tAltFrac": 0.21428571428571427,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "943": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.933)", "probably_damaging(1)"],
        "impact": ["MODERATE"],
        "tDepth": 90,
        "tAltCount": 36,
        "tAltFrac": 0.4,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "949": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 93,
        "tAltCount": 24,
        "tAltFrac": 0.25806451612903225,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "954": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 89,
        "tAltCount": 30,
        "tAltFrac": 0.33707865168539325,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "961": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 244,
        "tAltCount": 43,
        "tAltFrac": 0.1762295081967213,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "972": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.094)"],
        "impact": ["MODERATE"],
        "tDepth": 43,
        "tAltCount": 14,
        "tAltFrac": 0.32558139534883723,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "973": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(1)"],
        "impact": ["MODERATE"],
        "tDepth": 53,
        "tAltCount": 15,
        "tAltFrac": 0.2830188679245283,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "993": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(1)"],
        "impact": ["MODERATE"],
        "tDepth": 88,
        "tAltCount": 28,
        "tAltFrac": 0.3181818181818182,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1004": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.999)"],
        "impact": ["MODERATE"],
        "tDepth": 21,
        "tAltCount": 5,
        "tAltFrac": 0.23809523809523808,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1027": {
        "variantClassification": ["Frame_Shift_Del"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 115,
        "tAltCount": 33,
        "tAltFrac": 0.28695652173913044,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1046": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.904)"],
        "impact": ["MODERATE"],
        "tDepth": 23,
        "tAltCount": 5,
        "tAltFrac": 0.21739130434782608,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1076": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.002)"],
        "impact": ["MODERATE"],
        "tDepth": 80,
        "tAltCount": 29,
        "tAltFrac": 0.3625,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1078": {
        "variantClassification": ["5'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 12,
        "tAltCount": 5,
        "tAltFrac": 0.4166666666666667,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1081": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 46,
        "tAltCount": 18,
        "tAltFrac": 0.391304347826087,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1093": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 54,
        "tAltCount": 17,
        "tAltFrac": 0.3148148148148148,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1099": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 179,
        "tAltCount": 63,
        "tAltFrac": 0.35195530726256985,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1123": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 42,
        "tAltCount": 8,
        "tAltFrac": 0.19047619047619047,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1125": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.015)"],
        "impact": ["MODERATE"],
        "tDepth": 85,
        "tAltCount": 56,
        "tAltFrac": 0.6588235294117647,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1166": {
        "variantClassification": ["Intron", "Silent"],
        "polyPhen": [""],
        "impact": ["MODIFIER", "LOW"],
        "tDepth": 36,
        "tAltCount": 14,
        "tAltFrac": 0.45,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1175": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.444)", "benign(0.348)"],
        "impact": ["MODERATE"],
        "tDepth": 124,
        "tAltCount": 35,
        "tAltFrac": 0.47058823529411764,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1176": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 33,
        "tAltCount": 20,
        "tAltFrac": 0.6060606060606061,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1189": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.53)"],
        "impact": ["MODERATE"],
        "tDepth": 60,
        "tAltCount": 20,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1191": {
        "variantClassification": ["Splice_Region"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 49,
        "tAltCount": 28,
        "tAltFrac": 0.5714285714285714,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1196": {
        "variantClassification": ["Translation_Start_Site"],
        "polyPhen": ["possibly_damaging(0.621)"],
        "impact": ["HIGH"],
        "tDepth": 11,
        "tAltCount": 4,
        "tAltFrac": 0.36363636363636365,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1198": {
        "variantClassification": ["Nonsense_Mutation", "Splice_Site"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 85,
        "tAltCount": 15,
        "tAltFrac": 0.38235294117647056,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1199": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 271,
        "tAltCount": 95,
        "tAltFrac": 0.3505535055350554,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1200": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 29,
        "tAltCount": 15,
        "tAltFrac": 0.5172413793103449,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1206": {
        "variantClassification": ["Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 26,
        "tAltCount": 6,
        "tAltFrac": 0.23076923076923078,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1207": {
        "variantClassification": ["Missense_Mutation", "Silent"],
        "polyPhen": ["probably_damaging(0.952)", ""],
        "impact": ["MODERATE", "LOW"],
        "tDepth": 126,
        "tAltCount": 31,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1248": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.487)"],
        "impact": ["MODERATE"],
        "tDepth": 65,
        "tAltCount": 23,
        "tAltFrac": 0.35384615384615387,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1259": {
        "variantClassification": ["Missense_Mutation", "3'UTR"],
        "polyPhen": ["benign(0.004)", ""],
        "impact": ["MODERATE", "MODIFIER"],
        "tDepth": 116,
        "tAltCount": 43,
        "tAltFrac": 0.3706896551724138,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1267": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 137,
        "tAltCount": 50,
        "tAltFrac": 0.36496350364963503,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1271": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.001)"],
        "impact": ["MODERATE"],
        "tDepth": 89,
        "tAltCount": 34,
        "tAltFrac": 0.38202247191011235,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1289": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.003)"],
        "impact": ["MODERATE"],
        "tDepth": 34,
        "tAltCount": 11,
        "tAltFrac": 0.3235294117647059,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1291": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.001)"],
        "impact": ["MODERATE"],
        "tDepth": 96,
        "tAltCount": 27,
        "tAltFrac": 0.28125,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1309": {
        "variantClassification": ["3'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 39,
        "tAltCount": 17,
        "tAltFrac": 0.4358974358974359,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1332": {
        "variantClassification": ["Missense_Mutation", "Intron"],
        "polyPhen": ["probably_damaging(0.999)", "benign(0.01)", ""],
        "impact": ["MODERATE", "MODIFIER"],
        "tDepth": 90,
        "tAltCount": 20,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1338": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.364)"],
        "impact": ["MODERATE"],
        "tDepth": 34,
        "tAltCount": 11,
        "tAltFrac": 0.3235294117647059,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1349": {
        "variantClassification": ["Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 110,
        "tAltCount": 67,
        "tAltFrac": 0.6090909090909091,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1350": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.91)"],
        "impact": ["MODERATE"],
        "tDepth": 28,
        "tAltCount": 11,
        "tAltFrac": 0.39285714285714285,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1356": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.997)"],
        "impact": ["MODERATE"],
        "tDepth": 44,
        "tAltCount": 15,
        "tAltFrac": 0.3409090909090909,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1359": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 59,
        "tAltCount": 8,
        "tAltFrac": 0.13559322033898305,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1365": {
        "variantClassification": ["Missense_Mutation", "Nonsense_Mutation"],
        "polyPhen": ["probably_damaging(0.993)", ""],
        "impact": ["MODERATE", "HIGH"],
        "tDepth": 86,
        "tAltCount": 21,
        "tAltFrac": 0.25,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1366": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.044)"],
        "impact": ["MODERATE"],
        "tDepth": 74,
        "tAltCount": 15,
        "tAltFrac": 0.20270270270270271,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1373": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 84,
        "tAltCount": 27,
        "tAltFrac": 0.32142857142857145,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1384": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 17,
        "tAltCount": 5,
        "tAltFrac": 0.29411764705882354,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1392": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 41,
        "tAltCount": 12,
        "tAltFrac": 0.2926829268292683,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1395": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.006)", "possibly_damaging(0.469)"],
        "impact": ["MODERATE"],
        "tDepth": 69,
        "tAltCount": 25,
        "tAltFrac": 0.36231884057971014,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1400": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.868)"],
        "impact": ["MODERATE"],
        "tDepth": 41,
        "tAltCount": 10,
        "tAltFrac": 0.24390243902439024,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1434": {
        "variantClassification": ["5'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 9,
        "tAltCount": 5,
        "tAltFrac": 0.5555555555555556,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1440": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 105,
        "tAltCount": 35,
        "tAltFrac": 0.34146341463414637,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1451": {
        "variantClassification": ["Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 87,
        "tAltCount": 24,
        "tAltFrac": 0.27586206896551724,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1468": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.367)"],
        "impact": ["MODERATE"],
        "tDepth": 31,
        "tAltCount": 11,
        "tAltFrac": 0.3548387096774194,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1472": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.991)"],
        "impact": ["MODERATE"],
        "tDepth": 160,
        "tAltCount": 40,
        "tAltFrac": 0.25,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1477": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.106)"],
        "impact": ["MODERATE"],
        "tDepth": 351,
        "tAltCount": 62,
        "tAltFrac": 0.17663817663817663,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1485": {
        "variantClassification": ["5'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 49,
        "tAltCount": 13,
        "tAltFrac": 0.2653061224489796,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1492": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 63,
        "tAltCount": 24,
        "tAltFrac": 0.38095238095238093,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1493": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 116,
        "tAltCount": 8,
        "tAltFrac": 0.06896551724137931,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1500": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 14,
        "tAltCount": 7,
        "tAltFrac": 0.5,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1511": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.01)"],
        "impact": ["MODERATE"],
        "tDepth": 305,
        "tAltCount": 73,
        "tAltFrac": 0.23934426229508196,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1513": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.004)"],
        "impact": ["MODERATE"],
        "tDepth": 228,
        "tAltCount": 13,
        "tAltFrac": 0.05701754385964912,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1544": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(1)"],
        "impact": ["MODERATE"],
        "tDepth": 10,
        "tAltCount": 7,
        "tAltFrac": 0.7,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1561": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.246)"],
        "impact": ["MODERATE"],
        "tDepth": 57,
        "tAltCount": 13,
        "tAltFrac": 0.22807017543859648,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1570": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 43,
        "tAltCount": 11,
        "tAltFrac": 0.2558139534883721,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1588": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.056)"],
        "impact": ["MODERATE"],
        "tDepth": 24,
        "tAltCount": 4,
        "tAltFrac": 0.16666666666666666,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1610": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 61,
        "tAltCount": 15,
        "tAltFrac": 0.2459016393442623,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1614": {
        "variantClassification": ["Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 30,
        "tAltCount": 13,
        "tAltFrac": 0.43333333333333335,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1643": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 64,
        "tAltCount": 29,
        "tAltFrac": 0.453125,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1650": {
        "variantClassification": ["Splice_Site", "Missense_Mutation"],
        "polyPhen": ["", "probably_damaging(0.999)"],
        "impact": ["HIGH", "MODERATE"],
        "tDepth": 40,
        "tAltCount": 10,
        "tAltFrac": 0.25,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1652": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 151,
        "tAltCount": 35,
        "tAltFrac": 0.23178807947019867,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1665": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 40,
        "tAltCount": 10,
        "tAltFrac": 0.25,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1684": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.003)"],
        "impact": ["MODERATE"],
        "tDepth": 42,
        "tAltCount": 15,
        "tAltFrac": 0.35714285714285715,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1691": {
        "variantClassification": ["Silent", "Intron"],
        "polyPhen": [""],
        "impact": ["LOW", "MODIFIER"],
        "tDepth": 21,
        "tAltCount": 6,
        "tAltFrac": 0.2857142857142857,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1694": {
        "variantClassification": ["5'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 76,
        "tAltCount": 22,
        "tAltFrac": 0.2894736842105263,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1697": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 77,
        "tAltCount": 19,
        "tAltFrac": 0.24675324675324675,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1702": {
        "variantClassification": ["Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 16,
        "tAltCount": 6,
        "tAltFrac": 0.375,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1712": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.999)"],
        "impact": ["MODERATE"],
        "tDepth": 12,
        "tAltCount": 5,
        "tAltFrac": 0.4166666666666667,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1734": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.83)"],
        "impact": ["MODERATE"],
        "tDepth": 78,
        "tAltCount": 21,
        "tAltFrac": 0.2692307692307692,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1736": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.81)", "benign(0.036)"],
        "impact": ["MODERATE"],
        "tDepth": 63,
        "tAltCount": 25,
        "tAltFrac": 0.3968253968253968,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1745": {
        "variantClassification": ["Missense_Mutation", "Silent"],
        "polyPhen": ["probably_damaging(0.994)", ""],
        "impact": ["MODERATE", "LOW"],
        "tDepth": 70,
        "tAltCount": 19,
        "tAltFrac": 0.3235294117647059,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1755": {
        "variantClassification": ["Silent", "Missense_Mutation", "5'UTR"],
        "polyPhen": ["", "benign(0.435)"],
        "impact": ["LOW", "MODERATE", "MODIFIER"],
        "tDepth": 82,
        "tAltCount": 25,
        "tAltFrac": 0.3968253968253968,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1765": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 75,
        "tAltCount": 17,
        "tAltFrac": 0.22666666666666666,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1795": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 19,
        "tAltCount": 5,
        "tAltFrac": 0.2631578947368421,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1807": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.982)"],
        "impact": ["MODERATE"],
        "tDepth": 33,
        "tAltCount": 9,
        "tAltFrac": 0.2727272727272727,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1810": {
        "variantClassification": ["Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 8,
        "tAltCount": 4,
        "tAltFrac": 0.5,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1825": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.773)"],
        "impact": ["MODERATE"],
        "tDepth": 55,
        "tAltCount": 14,
        "tAltFrac": 0.2545454545454545,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1826": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.983)"],
        "impact": ["MODERATE"],
        "tDepth": 69,
        "tAltCount": 21,
        "tAltFrac": 0.30434782608695654,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1829": {
        "variantClassification": ["Silent", "Missense_Mutation"],
        "polyPhen": ["", "probably_damaging(1)"],
        "impact": ["LOW", "MODERATE"],
        "tDepth": 92,
        "tAltCount": 19,
        "tAltFrac": 0.23170731707317074,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1831": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.041)"],
        "impact": ["MODERATE"],
        "tDepth": 68,
        "tAltCount": 22,
        "tAltFrac": 0.3235294117647059,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1836": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 109,
        "tAltCount": 35,
        "tAltFrac": 0.3211009174311927,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1858": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.829)"],
        "impact": ["MODERATE"],
        "tDepth": 79,
        "tAltCount": 16,
        "tAltFrac": 0.20253164556962025,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1860": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.891)"],
        "impact": ["MODERATE"],
        "tDepth": 145,
        "tAltCount": 37,
        "tAltFrac": 0.25517241379310346,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1864": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.003)"],
        "impact": ["MODERATE"],
        "tDepth": 36,
        "tAltCount": 12,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1872": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 79,
        "tAltCount": 24,
        "tAltFrac": 0.3037974683544304,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1897": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 68,
        "tAltCount": 24,
        "tAltFrac": 0.35294117647058826,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1899": {
        "variantClassification": ["5'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 47,
        "tAltCount": 10,
        "tAltFrac": 0.2127659574468085,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1913": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 39,
        "tAltCount": 14,
        "tAltFrac": 0.358974358974359,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1917": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.766)"],
        "impact": ["MODERATE"],
        "tDepth": 46,
        "tAltCount": 23,
        "tAltFrac": 0.5,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1941": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.003)"],
        "impact": ["MODERATE"],
        "tDepth": 43,
        "tAltCount": 14,
        "tAltFrac": 0.32558139534883723,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1960": {
        "variantClassification": ["Translation_Start_Site", "Splice_Site"],
        "polyPhen": ["possibly_damaging(0.649)", ""],
        "impact": ["HIGH"],
        "tDepth": 75,
        "tAltCount": 20,
        "tAltFrac": 0.3191489361702128,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1965": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.992)"],
        "impact": ["MODERATE"],
        "tDepth": 27,
        "tAltCount": 11,
        "tAltFrac": 0.4074074074074074,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1966": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.122)"],
        "impact": ["MODERATE"],
        "tDepth": 113,
        "tAltCount": 38,
        "tAltFrac": 0.336283185840708,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "1968": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 24,
        "tAltCount": 7,
        "tAltFrac": 0.2916666666666667,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2005": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.694)"],
        "impact": ["MODERATE"],
        "tDepth": 43,
        "tAltCount": 20,
        "tAltFrac": 0.46511627906976744,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2014": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.502)", "possibly_damaging(0.486)"],
        "impact": ["MODERATE"],
        "tDepth": 47,
        "tAltCount": 10,
        "tAltFrac": 0.2413793103448276,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2027": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.013)"],
        "impact": ["MODERATE"],
        "tDepth": 49,
        "tAltCount": 17,
        "tAltFrac": 0.3469387755102041,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2029": {
        "variantClassification": ["RNA"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 80,
        "tAltCount": 27,
        "tAltFrac": 0.3375,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2043": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 41,
        "tAltCount": 13,
        "tAltFrac": 0.3170731707317073,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2060": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 92,
        "tAltCount": 38,
        "tAltFrac": 0.41304347826086957,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2093": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 12,
        "tAltCount": 6,
        "tAltFrac": 0.5,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2103": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 36,
        "tAltCount": 9,
        "tAltFrac": 0.25,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2146": {
        "variantClassification": ["3'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 17,
        "tAltCount": 8,
        "tAltFrac": 0.47058823529411764,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2147": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.772)", "possibly_damaging(0.859)"],
        "impact": ["MODERATE"],
        "tDepth": 30,
        "tAltCount": 16,
        "tAltFrac": 0.5333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2171": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 53,
        "tAltCount": 20,
        "tAltFrac": 0.37735849056603776,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2225": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 74,
        "tAltCount": 28,
        "tAltFrac": 0.3783783783783784,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2249": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 26,
        "tAltCount": 10,
        "tAltFrac": 0.38461538461538464,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2260": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 35,
        "tAltCount": 12,
        "tAltFrac": 0.34285714285714286,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2267": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 15,
        "tAltCount": 5,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2284": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.01)"],
        "impact": ["MODERATE"],
        "tDepth": 62,
        "tAltCount": 22,
        "tAltFrac": 0.3548387096774194,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2286": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 290,
        "tAltCount": 100,
        "tAltFrac": 0.3448275862068966,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2311": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.804)"],
        "impact": ["MODERATE"],
        "tDepth": 77,
        "tAltCount": 25,
        "tAltFrac": 0.3246753246753247,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2328": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.016)"],
        "impact": ["MODERATE"],
        "tDepth": 12,
        "tAltCount": 4,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2346": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 109,
        "tAltCount": 33,
        "tAltFrac": 0.30275229357798167,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2347": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 64,
        "tAltCount": 22,
        "tAltFrac": 0.34375,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2403": {
        "variantClassification": ["RNA"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 46,
        "tAltCount": 27,
        "tAltFrac": 0.5869565217391305,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2440": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.776)"],
        "impact": ["MODERATE"],
        "tDepth": 35,
        "tAltCount": 9,
        "tAltFrac": 0.2571428571428571,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2453": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.013)"],
        "impact": ["MODERATE"],
        "tDepth": 33,
        "tAltCount": 7,
        "tAltFrac": 0.21212121212121213,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2454": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.116)"],
        "impact": ["MODERATE"],
        "tDepth": 62,
        "tAltCount": 23,
        "tAltFrac": 0.3709677419354839,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2461": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 68,
        "tAltCount": 20,
        "tAltFrac": 0.29411764705882354,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2465": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 59,
        "tAltCount": 18,
        "tAltFrac": 0.3050847457627119,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2469": {
        "variantClassification": ["Splice_Region"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 91,
        "tAltCount": 28,
        "tAltFrac": 0.3076923076923077,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2473": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 78,
        "tAltCount": 28,
        "tAltFrac": 0.358974358974359,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2492": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.292)", "benign(0.403)"],
        "impact": ["MODERATE"],
        "tDepth": 88,
        "tAltCount": 32,
        "tAltFrac": 0.36363636363636365,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2499": {
        "variantClassification": ["Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 11,
        "tAltCount": 4,
        "tAltFrac": 0.36363636363636365,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2500": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.729)"],
        "impact": ["MODERATE"],
        "tDepth": 62,
        "tAltCount": 17,
        "tAltFrac": 0.27419354838709675,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2535": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 73,
        "tAltCount": 25,
        "tAltFrac": 0.3424657534246575,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2536": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.956)"],
        "impact": ["MODERATE"],
        "tDepth": 100,
        "tAltCount": 17,
        "tAltFrac": 0.17,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2537": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.045)"],
        "impact": ["MODERATE"],
        "tDepth": 40,
        "tAltCount": 11,
        "tAltFrac": 0.275,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2539": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.997)"],
        "impact": ["MODERATE"],
        "tDepth": 54,
        "tAltCount": 13,
        "tAltFrac": 0.24074074074074073,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2541": {
        "variantClassification": ["Silent"],
        "polyPhen": [""],
        "impact": ["LOW"],
        "tDepth": 36,
        "tAltCount": 12,
        "tAltFrac": 0.3333333333333333,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2544": {
        "variantClassification": ["Nonsense_Mutation"],
        "polyPhen": [""],
        "impact": ["HIGH"],
        "tDepth": 32,
        "tAltCount": 5,
        "tAltFrac": 0.15625,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2548": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.008)"],
        "impact": ["MODERATE"],
        "tDepth": 33,
        "tAltCount": 15,
        "tAltFrac": 0.45454545454545453,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2553": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.97)"],
        "impact": ["MODERATE"],
        "tDepth": 42,
        "tAltCount": 12,
        "tAltFrac": 0.2857142857142857,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2555": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.998)"],
        "impact": ["MODERATE"],
        "tDepth": 21,
        "tAltCount": 4,
        "tAltFrac": 0.19047619047619047,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2557": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.913)"],
        "impact": ["MODERATE"],
        "tDepth": 91,
        "tAltCount": 31,
        "tAltFrac": 0.34065934065934067,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2562": {
        "variantClassification": ["3'UTR"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 25,
        "tAltCount": 11,
        "tAltFrac": 0.44,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2571": {
        "variantClassification": ["3'UTR", "Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 34,
        "tAltCount": 10,
        "tAltFrac": 0.6666666666666666,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2574": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["possibly_damaging(0.856)"],
        "impact": ["MODERATE"],
        "tDepth": 65,
        "tAltCount": 19,
        "tAltFrac": 0.2923076923076923,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2586": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.02)"],
        "impact": ["MODERATE"],
        "tDepth": 98,
        "tAltCount": 31,
        "tAltFrac": 0.3163265306122449,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2589": {
        "variantClassification": ["Intron"],
        "polyPhen": [""],
        "impact": ["MODIFIER"],
        "tDepth": 55,
        "tAltCount": 23,
        "tAltFrac": 0.41818181818181815,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2600": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["probably_damaging(0.981)"],
        "impact": ["MODERATE"],
        "tDepth": 208,
        "tAltCount": 56,
        "tAltFrac": 0.2692307692307692,
        "drug": "Gemcitabine",
        "response": "Complete Response",
        "indication": "TCGA-BLCA",
        "numberOfMutationsInPatient": 4446
      },
      "2605": {
        "variantClassification": ["Missense_Mutation"],
        "polyPhen": ["benign(0.014)"],
        "impact": ["MODERATE"],
        "tDepth": 60,
        "tAltCount